set nocompatible              " be iMproved, required
filetype off                  " required
set shell=/bin/bash
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')



" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'


Plugin 'vim-airline/vim-airline'
Plugin 'bling/vim-bufferline'
Plugin 'octol/vim-cpp-enhanced-highlight'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'vim-syntastic/syntastic'
Plugin 'nightsense/plumber'
Plugin 'dylanaraps/wal'
call vundle#end()            " required
filetype plugin indent on    " required


call plug#begin('~/.vim/plugged')
Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }

" (Optional) Multi-entry selection UI.
Plug 'junegunn/fzf'
"
" " (Completion plugin option 1)
" Plug 'roxma/nvim-completion-manager'
" " (Completion plugin option 2)
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
call plug#end()

set colorcolumn=120
set smartindent tabstop=4 shiftwidth=4 expandtab
map - :Explore<cr>
nmap q :bn!<cr>
nmap Q :bd!<cr>
imap kk <Esc> 
nmap cpr O/* Copyright (c) 2013-2018 GomSpace A/S. All rights reserved. */<Esc>
nmap pcr O# Copyright (c) 2013-2018 GomSpace A/S. All rights reserved.<Esc>
nnoremap <C-b> :CtrlPBuffer<cr>

set laststatus=2
set number
syntax on
execute pathogen#infect()


"""""""""""""""""""""""""""""""""""
" SYNTASTIC
" Default syntastic settings
" Open bottom window with :Error and close with :lclose
" set statusline+=%#warningmsg#
" set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_c_checkers = ['cpp/verapp', 'clang_tidy', 'cppcheck', 'gcc', 'make']
let g:syntastic_cpp_checkers = ['cpp/verapp', 'clang_tidy', 'cppcheck', 'gcc', 'make']
let g:syntastic_cpp_verapp_args = "-p gomspace"
let g:syntastic_python_checkers = ['python/pycodestyle']
let g:syntastic_python_pycodestyle_args = "--max-line-length=120 --ignore=E402"

"""""""""""""""""""""""""""""""""
"AIRLINE
" remove stuff from airline
let g:airline_section_warning = ''
let g:airline_section_error = ''
let g:airline_section_z = ''

" Highlight all search results
set hlsearch
nnoremap <Space> :noh<cr>

" use autodir to find tags file
set tags=tags;

" Map 'm' to recording
nnoremap m q

" split right
set splitright


fun! JRUN( arg )
    :vne
    execute ':r !' . a:arg
endfunction

command! -nargs=+ JR call JRUN( '<args>' )

set term=rxvt-unicode-256color

let g:MyVimTips="off"
function! ToggleVimTips()
    if g:MyVimTips == "on"
        let g:MyVimTips="off"
        bd README.md
        pclose
    else
        let g:MyVimTips="on"
        pedit ~/git-repos/mydotfiles/README.md
    endif
endfunction
set previewheight=15
nnoremap <F4> :call ToggleVimTips()<CR>




let g:JjpTagShow="off"
function! ToggleTagShow()
    if g:JjpTagShow == "on"
        let g:JjpTagShow="off"
        pclose
    else
        let g:JjpTagShow="on"
        :exe "ptjump " . expand("<cword>")
    endif
endfunction

nnoremap <F5> :call ToggleTagShow()<CR>

" :Man support
runtime! ftplugin/man.vim

nnoremap <F9> :NERDTreeCWD<CR>
colo jpterm


set hidden

let g:LanguageClient_serverCommands = {
    \ 'c': ['/home/jjp/git-repos/cquery/build/release/bin/cquery'],
    \ }

nnoremap <silent> K :call LanguageClient#textDocument_hover()<CR>
nnoremap <silent> gd :call LanguageClient#textDocument_definition()<CR>
nnoremap <silent> <F2> :call LanguageClient#textDocument_rename()<CR>
